#include "libgl/pix_gl.h"

/* TEXTURE */
PFNGLACTIVETEXTUREPROC glActiveTexture; 
PFNGLBINDTEXTUREPROC glBindTexture; 
PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D; 
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D; 
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D; 
PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D; 
PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D; 
PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D; 
PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D; 
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D; 
PFNGLDELETETEXTURESPROC glDeleteTextures; 
PFNGLGENTEXTURESPROC glGenTextures;
PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
PFNGLGETTEXIMAGEPROC glGetTexImage; 
PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv; 
PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv; 
PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
PFNGLISTEXTUREPROC glIsTexture;
PFNGLTEXIMAGE1DPROC glTexImage1D; 
PFNGLTEXIMAGE2DPROC glTexImage2D; 
PFNGLTEXIMAGE3DPROC glTexImage3D; 
PFNGLTEXPARAMETERFPROC glTexParameterf; 
PFNGLTEXPARAMETERIPROC glTexParameteri; 
PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
/* RENDER */
PFNGLCLEARPROC glClear;
PFNGLCLEARCOLORPROC glClearColor; 
PFNGLCLEARDEPTHPROC glClearDepth; 
PFNGLCLEARSTENCILPROC glClearStencil; 
PFNGLDRAWBUFFERPROC glDrawBuffer;
PFNGLFINISHPROC glFinish;
PFNGLFLUSHPROC glFlush;
PFNGLREADBUFFERPROC glReadBuffer; 
PFNGLREADPIXELSPROC glReadPixels; 
/* FRAME BUFFERS */
PFNGLDRAWBUFFERSPROC glDrawBuffers;
/* SHADERS */
/* BUFFER OBJECTS */
/* STATE MANAGEMENT */
PFNGLVIEWPORTPROC glViewport; 
/* UTILITY */
/* QUERIES */
/* IMMEDIATE MODE */
PFNGLARRAYELEMENTPROC glArrayElement; 
PFNGLBEGINPROC glBegin; 
PFNGLCOLOR3BPROC glColor3b; 
PFNGLCOLOR3SPROC glColor3s;
PFNGLCOLOR3IPROC glColor3i;
PFNGLCOLOR3FPROC glColor3f;
PFNGLCOLOR3DPROC glColor3d;
PFNGLCOLOR3UBPROC glColor3ub; 
PFNGLCOLOR3USPROC glColor3us;
PFNGLCOLOR3UIPROC glColor3ui;
PFNGLCOLOR4BPROC glColor4b; 
PFNGLCOLOR4SPROC glColor4s;
PFNGLCOLOR4IPROC glColor4i;
PFNGLCOLOR4FPROC glColor4f;
PFNGLCOLOR4DPROC glColor4d;
PFNGLCOLOR4UBPROC glColor4ub; 
PFNGLCOLOR4USPROC glColor4us;
PFNGLCOLOR4UIPROC glColor4ui;
PFNGLENDPROC glEnd;
PFNGLEVALCOORD1FPROC glEvalCoord1f; 
PFNGLEVALCOORD1DPROC glEvalCoord1d;
PFNGLEVALCOORD2FPROC glEvalCoord2f;
PFNGLEVALCOORD2DPROC glEvalCoord2d;
PFNGLEVALMESH1PROC glEvalMesh1;
PFNGLEVALPOINT1PROC glEvalPoint1;
PFNGLEVALPOINT2PROC glEvalPoint2; 
PFNGLFOGCOORDFPROC glFogCoordf; 
PFNGLFOGCOORDDPROC glFogCoordd; 
PFNGLINDEXSPROC glIndexs;
PFNGLINDEXIPROC glIndexi;
PFNGLINDEXFPROC glIndexf;
PFNGLINDEXDPROC glIndexd;
PFNGLINDEXUBPROC glIndexub;
PFNGLMATERIALFPROC glMaterialf;
PFNGLMATERIALIPROC glMateriali; 
PFNGLMULTITEXCOORD1SPROC glMultiTexCoord1s; 
PFNGLMULTITEXCOORD1IPROC glMultiTexCoord1i; 
PFNGLMULTITEXCOORD1FPROC glMultiTexCoord1f; 
PFNGLMULTITEXCOORD1DPROC glMultiTexCoord1d; 
PFNGLMULTITEXCOORD2SPROC glMultiTexCoord2s; 
PFNGLMULTITEXCOORD2IPROC glMultiTexCoord2i; 
PFNGLMULTITEXCOORD2FPROC glMultiTexCoord2f; 
PFNGLMULTITEXCOORD2DPROC glMultiTexCoord2d; 
PFNGLMULTITEXCOORD3SPROC glMultiTexCoord3s; 
PFNGLMULTITEXCOORD3IPROC glMultiTexCoord3i; 
PFNGLMULTITEXCOORD3FPROC glMultiTexCoord3f; 
PFNGLMULTITEXCOORD3DPROC glMultiTexCoord3d; 
PFNGLMULTITEXCOORD4SPROC glMultiTexCoord4s; 
PFNGLMULTITEXCOORD4IPROC glMultiTexCoord4i; 
PFNGLMULTITEXCOORD4FPROC glMultiTexCoord4f; 
PFNGLMULTITEXCOORD4DPROC glMultiTexCoord4d; 
PFNGLNORMAL3BPROC glNormal3b; 
PFNGLNORMAL3DPROC glNormal3d; 
PFNGLNORMAL3FPROC glNormal3f; 
PFNGLNORMAL3IPROC glNormal3i; 
PFNGLNORMAL3SPROC glNormal3s; 
PFNGLSECONDARYCOLOR3BPROC glSecondaryColor3b;
PFNGLSECONDARYCOLOR3SPROC glSecondaryColor3s;
PFNGLSECONDARYCOLOR3IPROC glSecondaryColor3i;
PFNGLSECONDARYCOLOR3FPROC glSecondaryColor3f;
PFNGLSECONDARYCOLOR3DPROC glSecondaryColor3d;
PFNGLSECONDARYCOLOR3UBPROC glSecondaryColor3ub;
PFNGLSECONDARYCOLOR3USPROC glSecondaryColor3us;
PFNGLSECONDARYCOLOR3UIPROC glSecondaryColor3ui;
PFNGLTEXCOORD1SPROC glTexCoord1s; 
PFNGLTEXCOORD1IPROC glTexCoord1i; 
PFNGLTEXCOORD1FPROC glTexCoord1f; 
PFNGLTEXCOORD1DPROC glTexCoord1d; 
PFNGLTEXCOORD2SPROC glTexCoord2s; 
PFNGLTEXCOORD2IPROC glTexCoord2i; 
PFNGLTEXCOORD2FPROC glTexCoord2f; 
PFNGLTEXCOORD2DPROC glTexCoord2d; 
PFNGLTEXCOORD3SPROC glTexCoord3s; 
PFNGLTEXCOORD3IPROC glTexCoord3i; 
PFNGLTEXCOORD3FPROC glTexCoord3f; 
PFNGLTEXCOORD3DPROC glTexCoord3d; 
PFNGLTEXCOORD4SPROC glTexCoord4s; 
PFNGLTEXCOORD4IPROC glTexCoord4i; 
PFNGLTEXCOORD4FPROC glTexCoord4f; 
PFNGLTEXCOORD4DPROC glTexCoord4d; 
PFNGLVERTEX2SPROC glVertex2s; 
PFNGLVERTEX2IPROC glVertex2i; 
PFNGLVERTEX2FPROC glVertex2f; 
PFNGLVERTEX2DPROC glVertex2d; 
PFNGLVERTEX3SPROC glVertex3s; 
PFNGLVERTEX3IPROC glVertex3i; 
PFNGLVERTEX3FPROC glVertex3f; 
PFNGLVERTEX3DPROC glVertex3d; 
PFNGLVERTEX4S glVertex4s; 
PFNGLVERTEX4IPROC glVertex4i; 
PFNGLVERTEX4FPROC glVertex4f; 
PFNGLVERTEX4DPROC glVertex4d; 

void 
pxLoadGLFunctions(void)
{
    glActiveTexture = (PFNGLACTIVETEXTUREPROC) pxLoadGLFunction("glActiveTexture");
    glBindTexture = (PFNGLBINDTEXTUREPROC) pxLoadGLFunction("glBindTexture");
    glCompressedTexImage1D = (PFNGLCOMPRESSEDTEXIMAGE1DPROC) pxLoadGLFunction("glCompressedTexImage1D");
    glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC) pxLoadGLFunction("glCompressedTexImage2D");
    glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC) pxLoadGLFunction("glCompressedTexImage3D");
    glCompressedTexSubImage1D = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) pxLoadGLFunction("glCompressedTexSubImage1D");
    glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) pxLoadGLFunction("glCompressedTexSubImage2D");
    glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) pxLoadGLFunction("glCompressedTexSubImage3D");
    glCopyTexImage1D = (PFNGLCOPYTEXIMAGE1DPROC) pxLoadGLFunction("glCopyTexImage1D");
    glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC) pxLoadGLFunction("glCopyTexImage2D");
    glCopyTexSubImage1D = (PFNGLCOPYTEXSUBIMAGE1DPROC) pxLoadGLFunction("glCopyTexSubImage1D");
    glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC) pxLoadGLFunction("glCopyTexSubImage2D");
    glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC) pxLoadGLFunction("glCopyTexSubImage3D");
    glDeleteTextures = (PFNGLDELETETEXTURESPROC) pxLoadGLFunction("glDeleteTextures");
    glGenTextures = (PFNGLGENTEXTURESPROC) pxLoadGLFunction("glGenTextures");
    glGetCompressedTexImage = (PFNGLGETCOMPRESSEDTEXIMAGEPROC) pxLoadGLFunction("glGetCompressedTexImage");
    glGetTexImage = (PFNGLGETTEXIMAGEPROC) pxLoadGLFunction("glGetTexImage");
    glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC) pxLoadGLFunction("glGetTexLevelParameterfv");
    glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC) pxLoadGLFunction("glGetTexLevelParameteriv");
    glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC) pxLoadGLFunction("glGetTexParameterfv");
    glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC) pxLoadGLFunction("glGetTexParameteriv");
    glIsTexture = (PFNGLISTEXTUREPROC) pxLoadGLFunction("glIsTexture");
    glTexImage1D = (PFNGLTEXIMAGE1DPROC) pxLoadGLFunction("glTexImage1D");
    glTexImage2D = (PFNGLTEXIMAGE2DPROC) pxLoadGLFunction("glTexImage2D");
    glTexImage3D = (PFNGLTEXIMAGE3DPROC) pxLoadGLFunction("glTexImage3D");
    glTexParameterf = (PFNGLTEXPARAMETERFPROC) pxLoadGLFunction("glTexParameterf");
    glTexParameteri = (PFNGLTEXPARAMETERIPROC) pxLoadGLFunction("glTexParameteri");
    glTexSubImage1D = (PFNGLTEXSUBIMAGE1DPROC) pxLoadGLFunction("glTexSubImage1D");
    glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC) pxLoadGLFunction("glTexSubImage2D");
    glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC) pxLoadGLFunction("glTexSubImage3D");

    glClear = (PFNGLCLEARPROC) pxLoadGLFunction("glClear");
    glClearColor = (PFNGLCLEARCOLORPROC) pxLoadGLFunction("glClearColor");
    glClearDepth = (PFNGLCLEARDEPTHPROC) pxLoadGLFunction("glClearDepth");
    glClearStencil = (PFNGLCLEARSTENCILPROC) pxLoadGLFunction("glClearStencil");
    glDrawBuffer = (PFNGLDRAWBUFFERPROC) pxLoadGLFunction("glDrawBuffer");
    glFinish = (PFNGLFINISHPROC) pxLoadGLFunction("glFinish");
    glFlush = (PFNGLFLUSHPROC) pxLoadGLFunction("glFlush");
    glReadBuffer = (PFNGLREADBUFFERPROC) pxLoadGLFunction("glReadBuffer");
    glReadPixels = (PFNGLREADPIXELSPROC) pxLoadGLFunction("glReadPixels");

    glDrawBuffers = (PFNGLDRAWBUFFERSPROC) pxLoadGLFunction("glDrawBuffers");

    glViewport = (PFNGLVIEWPORTPROC) pxLoadGLFunction("glViewport");

    glArrayElement = (PFNGLARRAYELEMENTPROC) pxLoadGLFunction("glArrayElement");
    glBegin = (PFNGLBEGINPROC) pxLoadGLFunction("glBegin");
    glColor3b = (PFNGLCOLOR3BPROC) pxLoadGLFunction("glColor3b");
    glColor3s = (PFNGLCOLOR3SPROC) pxLoadGLFunction("glColor3s");
    glColor3i = (PFNGLCOLOR3IPROC) pxLoadGLFunction("glColor3i");
    glColor3f = (PFNGLCOLOR3FPROC) pxLoadGLFunction("glColor3f");
    glColor3d = (PFNGLCOLOR3DPROC) pxLoadGLFunction("glColor3d");
    glColor3ub = (PFNGLCOLOR3UBPROC) pxLoadGLFunction("glColor3ub");
    glColor3us = (PFNGLCOLOR3USPROC) pxLoadGLFunction("glColor3us");
    glColor3ui = (PFNGLCOLOR3UIPROC) pxLoadGLFunction("glColor3ui");
    glColor4b = (PFNGLCOLOR4BPROC) pxLoadGLFunction("glColor4b");
    glColor4s = (PFNGLCOLOR4SPROC) pxLoadGLFunction("glColor4s");
    glColor4i = (PFNGLCOLOR4IPROC) pxLoadGLFunction("glColor4i");
    glColor4f = (PFNGLCOLOR4FPROC) pxLoadGLFunction("glColor4f");
    glColor4d = (PFNGLCOLOR4DPROC) pxLoadGLFunction("glColor4d");
    glColor4ub = (PFNGLCOLOR4UBPROC) pxLoadGLFunction("glColor4ub");
    glColor4us = (PFNGLCOLOR4USPROC) pxLoadGLFunction("glColor4us");
    glColor4ui = (PFNGLCOLOR4UIPROC) pxLoadGLFunction("glColor4ui");
    glEnd = (PFNGLENDPROC) pxLoadGLFunction("glEnd");
    glEvalCoord1f = (PFNGLEVALCOORD1FPROC) pxLoadGLFunction("glEvalCoord1f");
    glEvalCoord1d = (PFNGLEVALCOORD1DPROC) pxLoadGLFunction("glEvalCoord1d");
    glEvalCoord2f = (PFNGLEVALCOORD2FPROC) pxLoadGLFunction("glEvalCoord2f");
    glEvalCoord2d = (PFNGLEVALCOORD2DPROC) pxLoadGLFunction("glEvalCoord2d");
    glEvalMesh1 = (PFNGLEVALMESH1PROC) pxLoadGLFunction("glEvalMesh1");
    glEvalPoint1 = (PFNGLEVALPOINT1PROC) pxLoadGLFunction("glEvalPoint1");
    glEvalPoint2 = (PFNGLEVALPOINT2PROC) pxLoadGLFunction("glEvalPoint2");
    glFogCoordf = (PFNGLFOGCOORDFPROC) pxLoadGLFunction("glFogCoordf");
    glFogCoordd = (PFNGLFOGCOORDDPROC) pxLoadGLFunction("glFogCoordd");
    glIndexs = (PFNGLINDEXSPROC) pxLoadGLFunction("glIndexs");
    glIndexi = (PFNGLINDEXIPROC) pxLoadGLFunction("glIndexi");
    glIndexf = (PFNGLINDEXFPROC) pxLoadGLFunction("glIndexf");
    glIndexd = (PFNGLINDEXDPROC) pxLoadGLFunction("glIndexd");
    glIndexub = (PFNGLINDEXUBPROC) pxLoadGLFunction("glIndexub");
    glMaterialf = (PFNGLMATERIALFPROC) pxLoadGLFunction("glMaterialf");
    glMateriali = (PFNGLMATERIALIPROC) pxLoadGLFunction("glMateriali");
    glMultiTexCoord1s = (PFNGLMULTITEXCOORD1SPROC) pxLoadGLFunction("glMultiTexCoord1s");
    glMultiTexCoord1i = (PFNGLMULTITEXCOORD1IPROC) pxLoadGLFunction("glMultiTexCoord1i");
    glMultiTexCoord1f = (PFNGLMULTITEXCOORD1FPROC) pxLoadGLFunction("glMultiTexCoord1f");
    glMultiTexCoord1d = (PFNGLMULTITEXCOORD1DPROC) pxLoadGLFunction("glMultiTexCoord1d");
    glMultiTexCoord2s = (PFNGLMULTITEXCOORD2SPROC) pxLoadGLFunction("glMultiTexCoord2s");
    glMultiTexCoord2i = (PFNGLMULTITEXCOORD2IPROC) pxLoadGLFunction("glMultiTexCoord2i");
    glMultiTexCoord2f = (PFNGLMULTITEXCOORD2FPROC) pxLoadGLFunction("glMultiTexCoord2f");
    glMultiTexCoord2d = (PFNGLMULTITEXCOORD2DPROC) pxLoadGLFunction("glMultiTexCoord2d");
    glMultiTexCoord3s = (PFNGLMULTITEXCOORD3SPROC) pxLoadGLFunction("glMultiTexCoord3s");
    glMultiTexCoord3i = (PFNGLMULTITEXCOORD3IPROC) pxLoadGLFunction("glMultiTexCoord3i");
    glMultiTexCoord3f = (PFNGLMULTITEXCOORD3FPROC) pxLoadGLFunction("glMultiTexCoord3f");
    glMultiTexCoord3d = (PFNGLMULTITEXCOORD3DPROC) pxLoadGLFunction("glMultiTexCoord3d");
    glMultiTexCoord4s = (PFNGLMULTITEXCOORD4SPROC) pxLoadGLFunction("glMultiTexCoord4s");
    glMultiTexCoord4i = (PFNGLMULTITEXCOORD4IPROC) pxLoadGLFunction("glMultiTexCoord4i");
    glMultiTexCoord4f = (PFNGLMULTITEXCOORD4FPROC) pxLoadGLFunction("glMultiTexCoord4f");
    glMultiTexCoord4d = (PFNGLMULTITEXCOORD4DPROC) pxLoadGLFunction("glMultiTexCoord4d");
    glNormal3b = (PFNGLNORMAL3BPROC) pxLoadGLFunction("glNormal3b");
    glNormal3d = (PFNGLNORMAL3DPROC) pxLoadGLFunction("glNormal3d");
    glNormal3f = (PFNGLNORMAL3FPROC) pxLoadGLFunction("glNormal3f");
    glNormal3i = (PFNGLNORMAL3IPROC) pxLoadGLFunction("glNormal3i");
    glNormal3s = (PFNGLNORMAL3SPROC) pxLoadGLFunction("glNormal3s");
    glSecondaryColor3b = (PFNGLSECONDARYCOLOR3BPROC) pxLoadGLFunction("glSecondaryColor3b");
    glSecondaryColor3s = (PFNGLSECONDARYCOLOR3SPROC) pxLoadGLFunction("glSecondaryColor3s");
    glSecondaryColor3i = (PFNGLSECONDARYCOLOR3IPROC) pxLoadGLFunction("glSecondaryColor3i");
    glSecondaryColor3f = (PFNGLSECONDARYCOLOR3FPROC) pxLoadGLFunction("glSecondaryColor3f");
    glSecondaryColor3d = (PFNGLSECONDARYCOLOR3DPROC) pxLoadGLFunction("glSecondaryColor3d");
    glSecondaryColor3ub = (PFNGLSECONDARYCOLOR3UBPROC) pxLoadGLFunction("glSecondaryColor3ub");
    glSecondaryColor3us = (PFNGLSECONDARYCOLOR3USPROC) pxLoadGLFunction("glSecondaryColor3us");
    glSecondaryColor3ui = (PFNGLSECONDARYCOLOR3UIPROC) pxLoadGLFunction("glSecondaryColor3ui");
    glTexCoord1s = (PFNGLTEXCOORD1SPROC) pxLoadGLFunction("glTexCoord1s");
    glTexCoord1i = (PFNGLTEXCOORD1IPROC) pxLoadGLFunction("glTexCoord1i");
    glTexCoord1f = (PFNGLTEXCOORD1FPROC) pxLoadGLFunction("glTexCoord1f");
    glTexCoord1d = (PFNGLTEXCOORD1DPROC) pxLoadGLFunction("glTexCoord1d");
    glTexCoord2s = (PFNGLTEXCOORD2SPROC) pxLoadGLFunction("glTexCoord2s");
    glTexCoord2i = (PFNGLTEXCOORD2IPROC) pxLoadGLFunction("glTexCoord2i");
    glTexCoord2f = (PFNGLTEXCOORD2FPROC) pxLoadGLFunction("glTexCoord2f");
    glTexCoord2d = (PFNGLTEXCOORD2DPROC) pxLoadGLFunction("glTexCoord2d");
    glTexCoord3s = (PFNGLTEXCOORD3SPROC) pxLoadGLFunction("glTexCoord3s");
    glTexCoord3i = (PFNGLTEXCOORD3IPROC) pxLoadGLFunction("glTexCoord3i");
    glTexCoord3f = (PFNGLTEXCOORD3FPROC) pxLoadGLFunction("glTexCoord3f");
    glTexCoord3d = (PFNGLTEXCOORD3DPROC) pxLoadGLFunction("glTexCoord3d");
    glTexCoord4s = (PFNGLTEXCOORD4SPROC) pxLoadGLFunction("glTexCoord4s");
    glTexCoord4i = (PFNGLTEXCOORD4IPROC) pxLoadGLFunction("glTexCoord4i");
    glTexCoord4f = (PFNGLTEXCOORD4FPROC) pxLoadGLFunction("glTexCoord4f");
    glTexCoord4d = (PFNGLTEXCOORD4DPROC) pxLoadGLFunction("glTexCoord4d");
    glVertex2s = (PFNGLVERTEX2SPROC) pxLoadGLFunction("glVertex2s");
    glVertex2i = (PFNGLVERTEX2IPROC) pxLoadGLFunction("glVertex2i");
    glVertex2f = (PFNGLVERTEX2FPROC) pxLoadGLFunction("glVertex2f");
    glVertex2d = (PFNGLVERTEX2DPROC) pxLoadGLFunction("glVertex2d");
    glVertex3s = (PFNGLVERTEX3SPROC) pxLoadGLFunction("glVertex3s");
    glVertex3i = (PFNGLVERTEX3IPROC) pxLoadGLFunction("glVertex3i");
    glVertex3f = (PFNGLVERTEX3FPROC) pxLoadGLFunction("glVertex3f");
    glVertex3d = (PFNGLVERTEX3DPROC) pxLoadGLFunction("glVertex3d");
    glVertex4s = (PFNGLVERTEX4S) pxLoadGLFunction("glVertex4s");
    glVertex4i = (PFNGLVERTEX4IPROC) pxLoadGLFunction("glVertex4i");
    glVertex4f = (PFNGLVERTEX4FPROC) pxLoadGLFunction("glVertex4f");
    glVertex4d = (PFNGLVERTEX4DPROC) pxLoadGLFunction("glVertex4d");
}
